name: Node.js CI for React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 👈 Enables manual trigger from GitHub UI

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-app

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: 🔄 Checkout Repository
      uses: actions/checkout@v4

    - name: 🧪 Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: 📦 Install Dependencies
      run: npm install

    - name: ✅ Run Build
      run: npm run build

    - name: 🧪 Run Tests
      run: npm test -- --watchAll=false
